[site]
name = "Move2Augusta"
style = "tech"
icon = "media/favicon.ico"

[menu]
names = ["Home", "Apartments", "Contributing"]
links = ["/", "/apartments", "/contributing"]

[media]
include = [
    "apartment.jpg",
]
